version: '3.8'
services:
  postgres:
    image: postgres
    container_name: my-postgres
    restart: always
    ports:
      - "5431:5431"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
