version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres-orders
    restart: unless-stopped
    ports:
      - "5332:5432"
    environment:
      POSTGRES_DB: Orders_DB
      POSTGRES_PASSWORD: admin_joao
      POSTGRES_USER: admin_joao
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
networks:
  db:
    driver: bridge

volumes:
  db:
