services:
  postgresdb:
    image: postgres:latest
    container_name: postgres-orders
    restart: unless-stopped
    ports:
      - "5332:5432"
    environment:
      POSTGRES_DB: Orders_DB
      POSTGRES_PASSWORD: admin_joao
      POSTGRES_USER: admin_joao
      PGDATA: /data/postgres
    volumes:
      - postgresdb:/data/postgres
#  mongodb:
#    image: mongodb/mongodb-community-server:6.0-ubi8
#    container_name: mongodb-payments-service
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin_joao
#      - MONGO_INITDB_ROOT_PASSWORD=admin_joao
#    volumes:
#      - type: bind
#        source: ./data
#        target: /data/db
networks:
  postgresdb:
    driver: bridge

volumes:
  postgresdb:
